function [ unitsdecoding ] = sixtwocompare( units )
%SIXTWOCOMPARE Summary of this function goes here
%   Detailed explanation goes here
switch units
    case '0'
         unitsdecoding= 0*1;
    case '1'
         unitsdecoding= 1*1;
    case '2'
         unitsdecoding= 2*1;
    case '3'
         unitsdecoding= 3*1;
    case '4'
         unitsdecoding= 4*1;
    case '5'
         unitsdecoding= 5*1;
    case '6'
         unitsdecoding= 6*1;
    case '7'
         unitsdecoding= 7*1;
    case '8'
         unitsdecoding= 8*1;
    case '9'
         unitsdecoding= 9*1;
    case 'a'
         unitsdecoding= 10*1;
    case 'b'
         unitsdecoding= 11*1;
    case 'c'
         unitsdecoding= 12*1;
    case 'd'
         unitsdecoding= 13*1;
    case 'e'
         unitsdecoding= 14*1;
    case 'f'
         unitsdecoding= 15*1;
    case 'g'
         unitsdecoding= 16*1;
    case 'h'
         unitsdecoding= 17*1;
    case 'i'
         unitsdecoding= 18*1;
    case 'j'
         unitsdecoding= 19*1;
    case 'k'
         unitsdecoding= 20*1;
    case 'l'
         unitsdecoding= 21*1;
    case 'm'
         unitsdecoding= 22*1;
    case 'n'
         unitsdecoding= 23*1;
    case 'o'
         unitsdecoding= 24*1;
    case 'p'
         unitsdecoding= 25*1;
    case 'q'
         unitsdecoding= 26*1;
    case 'r'
         unitsdecoding= 27*1;
    case 's'
         unitsdecoding= 28*1;
    case 't'
         unitsdecoding= 29*1;
    case 'u'
         unitsdecoding= 30*1;
    case 'v'
         unitsdecoding= 31*1;
    case 'w'
         unitsdecoding= 32*1;
    case 'x'
         unitsdecoding= 33*1;
    case 'y'
         unitsdecoding= 34*1;
    case 'z'
         unitsdecoding= 35*1;
    case 'A'
         unitsdecoding= 36*1;
    case 'B'
         unitsdecoding= 37*1;
    case 'C'
         unitsdecoding= 38*1;
    case 'D'
         unitsdecoding= 39*1;
    case 'E'
         unitsdecoding= 40*1;
    case 'F'
         unitsdecoding= 41*1;
    case 'G'
         unitsdecoding= 42*1;
    case 'H'
         unitsdecoding= 43*1;
    case 'I'
         unitsdecoding= 44*1;
    case 'J'
         unitsdecoding= 45*1;
    case 'K'
         unitsdecoding= 46*1;
    case 'L'
         unitsdecoding= 47*1;
    case 'M'
         unitsdecoding= 48*1;
    case 'N'
         unitsdecoding= 49*1;
    case 'O'
         unitsdecoding= 50*1;
    case 'P'
         unitsdecoding= 51*1;
    case 'Q'
         unitsdecoding= 52*1;
    case 'R'
         unitsdecoding= 53*1;
    case 'S'
         unitsdecoding= 54*1;
    case 'T'
         unitsdecoding= 55*1;
    case 'U'
         unitsdecoding= 56*1;
    case 'V'
         unitsdecoding= 57*1;
    case 'W'
         unitsdecoding= 58*1;
    case 'X'
         unitsdecoding= 59*1;
    case 'Y'
         unitsdecoding= 60*1;
    case 'Z'
         unitsdecoding= 61*1;
   
end

end

